apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: elasticsearch-s3-secret
spec:
    secretTemplates:
        - name: aws-credentials
          labels:
            app: judilibre-es
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CRELRA==,iv:htPQ3sxXHdmdZ9FPogyM8x0NwzEOwNakV2JLklEHw+o=,tag:r5uLfQk6AXp1fUEl+plDmQ==,type:str]
          data:
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9aAj6Q==,iv:SIl4iaa8rzTOHIw3vX4m3VTY7eRmOWeQgQFpVPUPVv8=,tag:RqSBk49B92t1A/vUJNOmhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVkdMUjBENCtMRzBBNjFX
            a3V0NkRZY1h2SkRiWW5hV1BzU1B6cXBlUDFJClBVN3d5eExBUzVlZUNUYXBPMXRo
            RHl3c25wMWE5RXV0N2JyUGxCRE9CMEkKLS0tIDQyUnZQeGltbjgyYnExaW9ZK00y
            cElVUU5qYXdvdFA5dWR4WDZ1Q2x5UVkKcpRD7G1CLGrqnIvC6Y+aSsCaNMi+gq8/
            NLZ0uqfq1h42RdKvy4VkYZX+0v+vjQQ3DqWY1zcInJw0AL9Y/YxxHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T15:41:16Z"
    mac: ENC[AES256_GCM,data:ulTYioxeipvCT/mg9IJ8YQJJjJ8XdX/HGvBjqG4Jtf9TIEznwNOgWaPPfCbBVwN7njrHpdyZG6qD5GUBfQZ71g6imWonBkjiIUSB9VYFthP1t1OyFYpvsCJhlx6HSURknekC3QZ3PO/jAAsEQL7ER/B0Mhp9j2HoFqmWV+71lcE=,iv:OLxkuhG+i2IGGfUS9wldnKJbSu7xfm+VxkNJFFEQj70=,tag:33R1JPNbyaGqtG7d1t/dSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
