apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: elasticsearch-s3-secret
spec:
    secretTemplates:
        - name: aws-credentials
          labels:
            app: judilibre-es
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fvIDvsnntBks+/RM7QEW4HBGhlE=,iv:Hz787qRePWmVLvzIy07TUztObgukx/+ZdDmPOzhMr4E=,tag:8h/sqBGZ491Bd6N57p4j2A==,type:str]
          data:
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jfhmtzSmxIEWfnGahwrv//izE5GdJ8PxBpQGaVt08cYSyzl/,iv:kYIf+mlPpq4NDrmI4kiNOos+5hcEi7RXKrLlBjGZdoY=,tag:hDL5aCjVdYnRpcpey+7JpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU1czUDRGTFo5aCttWjNZ
            bVNvRG1GWlQzM0lnSEhMbC9wK0lpQWQyTkR3CnNuMUQzVE1LRGdqR0xhd1A5Smd2
            bzdxeVNiUHVSbXZNOTNma0t6VUJHSlUKLS0tIHI0TFhRV0YrV3ZkNVQ2L0pMNDFh
            Y21oaXpYc2xBdFg1OEUyQjNEak41VmsK4fqYGFSiAohDi3FF6Yid4Q7V04kdjYEt
            zF+cz9M+8xcclLXwPmH9v0Cs0C/rsm6W3Na5IcrGk+ETiz7tqKEGEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T10:26:53Z"
    mac: ENC[AES256_GCM,data:5qifSWRgIV0hgoHkkbvht6ptUI11m8yysaqKLPMJyuaEV1mVpSXlrkjAnGleeDfTemNKM6I5NOtjaD+zNIfsdHxG4x1Kd9lFLCtaSl6n4lTV3kiOPK7aYm59G8/ATSyz+lhkRccILIsVZ68HTGEsG+TuyCgu9HXfjbUNSQ1tf3g=,iv:zjZ8AYO3EicbuaApY/wSH6AoTYsjd5NXhADHnteOWQs=,tag:BUkSbceC2MCwtoNYUkpO7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
