apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: elasticsearch-s3-secret
spec:
    secretTemplates:
        - name: aws-credentials
          labels:
            app: judilibre-es
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3vCjg5WOWVv5V4/58BI32XRpgy0=,iv:dCMOCKnCiBEwK793sv7LE421lpXSdj/DC4DNOMv07LQ=,tag:P5HFg/mNpKRw0aUty+Vg4w==,type:str]
          data:
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tZflBLEN9eJXTxO7Ozij/ryYtHNJ8zumHX2SzW5BDEInKF0Yu7gZD2xkdYBaXaFRpfp6IA==,iv:mpltcjt/NoxfQbnq4PWGXrQEMZIY69LZ7ShwzAKZwtU=,tag:nDuuK5RyroU7kJ13X8nRTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFdBc0V6aXU1bWE2cXMz
            Q0hMeFVxSDRTa1RhWTM3VTlISnpRemdDckJZCkVCVVVERXMzK01BSUJPV1ZCY3Uy
            TVZ6VVY2Nm9zSy9BRHNnQ0hYa0EvYVEKLS0tIFJUM2M4UE5rcUhTSTFKWXJMMUdh
            a0J6VDJTRG41ZERTVG5JU0p5SXplNncK5gquU9sOIpZdbyF7S0xQ0ktF39M+jCCa
            19tyn+h4QOYNpctM9QfnTG+ablCgmPrnyd71qw5IMjeH3UyK1poJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T14:34:02Z"
    mac: ENC[AES256_GCM,data:PNN0KtEPJu2wpAmOa6XhXoKgS90ELPVSGy9aRZyjinrPpDxjplEINhaXphImq7zyKRqjgVlCmyPEjmRb/EnmJKFmgr+bIiziJfrgxt31VuROX6HDLVShBie79dB8tKBwvf6VV+ZGzipK/dCfsw3/6UVOrBgeW+qbJ8heLZ33BKI=,iv:ZiyoyM8YsQExkzqHUWVEbDOWUaz+bfbAy0aeSk7Q9Wc=,tag:N2P5wGpxNfvuT/TP/0aZBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
